[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build && cp src/db/schema.sql dist/db/schema.sql"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
healthcheckPath = "/health"
